# Generated by Django 6.0.1 on 2026-02-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicostatus',
            options={'verbose_name': 'Histórico de Status', 'verbose_name_plural': 'Históricos de Status'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
