# Generated by Django 6.0.1 on 2026-02-18 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_alter_chamado_options_alter_historicostatus_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
